"""Add User's About Me 

Revision ID: 9317d9c101bf
Revises: 0eb533ee3435
Create Date: 2022-12-17 14:45:32.581303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9317d9c101bf'
down_revision = '0eb533ee3435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
